codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "60...85"

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
