repos:
- repo: git://github.com/dnephin/pre-commit-golang
  rev: v0.3.5
  hooks:
  - id: go-fmt
  - id: go-lint
  - id: validate-toml
  - id: no-go-testing
- repo: https://github.com/bmorcos/pre-commit-hooks-cpp
  rev: master
  hooks:
  - id: cpplint
